name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    # https://docs.docker.com/build/ci/github-actions/local-registry/
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000

    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-buildx-action@v3
    - uses: docker/build-push-action@v5
      with:
        context: "{{defaultContext}}:buildenv_rust"
        cache-from: type=gha
        cache-to: type=gha,mode=max
        push: true
        tags: localhost:5000/jos/buildenv_rust:latest

    - name: Run the build process with Docker
      run: |
        make build-x86_64

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
