name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-buildx-action@v3
    - uses: docker/build-push-action@v5
      with:
        context: "{{defaultContext}}:buildenv_rust"
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Run the build process with Docker
      uses: addnab/docker-run-action@v3
      with:
          image: jos/buildenv:latest
          options: -v "${pwd}:/root/env"
          run: |
            make build-x86_64

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
